# Generated by Django 2.2.5 on 2021-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('student_dob', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
