# Generated by Django 2.2.5 on 2021-03-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='description_data',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice',
            new_name='notice_title',
        ),
    ]
