# Generated by Django 2.2.5 on 2021-03-10 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210309_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_year', models.IntegerField(null='true')),
                ('p_amount', models.IntegerField(null='true')),
                ('p_type', models.CharField(max_length=50)),
                ('p_details', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
