# Generated by Django 2.2.5 on 2021-03-10 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
    ]
