# Generated by Django 2.2.5 on 2021-03-10 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210310_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
