# Generated by Django 2.2.5 on 2021-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210310_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_surname', models.CharField(max_length=50)),
                ('s_sem', models.IntegerField(null='true')),
                ('s_branch', models.CharField(max_length=50)),
                ('s_room', models.IntegerField(null='true')),
            ],
        ),
    ]
