# Generated by Django 2.2.5 on 2021-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_addstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_roomno',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
    ]
